language: go
go:
  - 1.6.3
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout v0.11.1 && go install && cd -
  - glide install
after_success:
  - sh `pwd`/scripts/coverage --coveralls
