clone_folder: c:\gopath\src\github.com\wedeploy\cli
environment:
  GOPATH: c:\gopath
install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout v0.11.1 && go install && cd -
  - glide install
build_script:
  - go test -v $(glide novendor)
